<TimeModule>
	BoxLayout:
		orientation:"vertical"
		Label:
			id: TimeLabel
			text: root.timeString
			font_size: '50sp'
		Label:
			id: DateLabel
			text: root.dateString
			font_size: '25sp'

<UpperRowModule>
	BoxLayout:
		orientation:"horizontal"
		TimeModule:
			id: timeMod
		Label:
			text: "YEAH BOI"

<LowerRowModule>

<RPiCLock>
	BoxLayout:
		orientation:"vertical"
		UpperRowModule:
			id: UpperRow
		LowerRowModule:
			id: LowerRow